### ISSUE TITLE
grd in GeoData

### ISSUE THREAD

**Issue by rafaqz** [mkborregaard/VerySimpleRasters.jl#3]
Hi Michael, Just letting you know I've copied a bunch of the grd code from this repo over to GeoData.jl: https://github.com/rafaqz/GeoData.jl/blob/master/src/sources/grd.jl

See the tests for examples of how it works.
https://github.com/rafaqz/GeoData.jl/blob/master/test/grd.jl

I've credited you as a package author.

**Comment by mkborregaard** [comment]
Hi @rafaqz great, nice if it's useful!
I can't see where you've credited me but it's fine either way.

**Comment by rafaqz** [comment]
In the license :)

https://github.com/rafaqz/GeoData.jl/blob/master/LICENSE

**Comment by mkborregaard** [comment]
Oh :-D :heart:
